import sqlite3

DATABASE_FILE = "security.db"


def get_connection():
    return sqlite3.connect(DATABASE_FILE)


def initialize_database():

    connection = get_connection()
    cursor = connection.cursor()

    # Raw authentication events
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            source_ip TEXT,
            username TEXT,
            event_type TEXT NOT NULL,
            UNIQUE(timestamp, source_ip, username, event_type)
        )
    """)

    # Security alerts generated by detection rules
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            severity TEXT NOT NULL,
            alert_type TEXT NOT NULL,
            source_ip TEXT,
            username TEXT,
            event_count INTEGER,
            description TEXT,
            UNIQUE(
                timestamp,
                severity,
                alert_type,
                source_ip,
                username
            )
        )
    """)

    connection.commit()
    connection.close()


def insert_event(event):

    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        INSERT OR IGNORE INTO events (
            timestamp,
            source_ip,
            username,
            event_type
        )
        VALUES (?, ?, ?, ?)
    """, (
        event["timestamp"].strftime(
            "%Y-%m-%d %H:%M:%S"
        ),
        event["source_ip"],
        event["username"],
        event["event_type"]
    ))

    connection.commit()
    connection.close()


def insert_alert(alert):

    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        INSERT OR IGNORE INTO alerts (
            timestamp,
            severity,
            alert_type,
            source_ip,
            username,
            event_count,
            description
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (
        alert["timestamp"].strftime(
            "%Y-%m-%d %H:%M:%S"
        ),
        alert["severity"],
        alert["alert_type"],
        alert["source_ip"],
        alert["username"],
        alert["event_count"],
        alert["description"]
    ))

    connection.commit()
    connection.close()